# Generated by Django 5.2.4 on 2025-07-08 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_avatar_profile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='Description',
        ),
    ]
