# Generated by Django 5.2.4 on 2025-07-08 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_bio_profile_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Description',
            new_name='description',
        ),
    ]
